### ISSUE TITLE
[REFACTOR] Combine Observer & Audience Class

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [jeong-hyeonHwang/MultipeerTest#3]
### 문제 상황
- Observer와 Audience 분리를 통해 서로의 역할을 구분하던 형태였으나, 중복되는 코드가 너무 많음

### 해결 방법
- Observer와 Audience 클래스를 합치자

### TODO
- [x] Multipeer Connectivity 다시 공부하기 (공식 Document 참고)
- [ ] 앱의 기본적인 Logic 재설계
- [ ] SwiftUI -> UIKit에서 사용할 수 있는 형태로 변경하기

**Comment by jeong-hyeonHwang** [comment]
### Multipeer Connectivity
- 공식 Document(https://developer.apple.com/documentation/multipeerconnectivity) 를 기반으로 작성했습니다
![Multipeer Connectivity-2](https://user-images.githubusercontent.com/96641477/179505310-77c8c9ce-2615-43a9-a392-0604dfe9bf1a.jpg)
